-- Create The Table Structure --
CREATE TABLE Coffee_Shop_Sales (
   transaction_id integer,
   transaction_date date,
   transaction_time time,
   transaction_qty int,
   store_id int,
   store_location varchar,
   product_id int,
   unit_price decimal(10,2),
   product_category varchar,
   product_type varchar,
   product_detail varchar
)

--- Import CSV Data ---
copy Coffee_Shop_Sales
from 'E:\Program Files\PostgreSQL\18\data\Coffee Shop Sales.csv'
delimiter ','
csv header;

Select * from Coffee_Shop_Sales;

/*

I) Product Sales Analysis :-   
   
Top 5 Most Frequently Sold Products by Product Category :- 

1) Retrieve the top 5 products with the highest sales frequency within each product category.

Purpose :-  Identify the most popular products to inform inventory management and marketing strategies.

*/

-- Ans 1 ---
Select product_id , product_category , sum(transaction_qty) as total_quantity_sold 
from Coffee_Shop_Sales group by product_id , product_category order by total_quantity_sold desc limit 5;

/*
   
II) Monthly Revenue Calculation :- 

Total Revenue Generated by Each Store in January 2023 :- 

2) Calculate the total revenue for each store during January 2023.

Purpose :-  Assess store performance and compare revenue across different locations for that month.

*/

-- Ans 2 --
Select store_id , store_location , sum(transaction_qty * unit_price) as total_quantity_sold 
from Coffee_Shop_Sales where transaction_date between '2023-01-01' and '2023-01-31'
group by store_id , store_location;

/*
  
III) Product Variety in Specific Location :- 

Unique Product Types Sold in 'Lower Manhattan' Store :- 

3) List all unique product types sold in the store located in Lower Manhattan.

Purpose :-  Understand the product range available at this location to tailor offerings or promotions.

*/

-- Ans 3 --
Select distinct product_type from Coffee_Shop_Sales where store_location='Lower Manhattan';

/*

IV) Transaction Timing Analysis:

Total Number of Transactions Before 12:00 PM :- 

4) Calculate the total number of transactions that occurred before 12:00 PM on any given day.

Purpose :- Optimize staffing and resource allocation during morning hours.

*/

-- Ans 4 --
Select count(transaction_id) as total_no_of_transactions from Coffee_Shop_Sales where transaction_time < '12:00:00';

/*

V) Revenue Per Transaction Analysis :- 

Average Revenue per Transaction for Each Product Category During Peak and Non-Peak Hours :-

5) Find the average revenue per transaction for each product category during peak hours (7 AM - 9 AM) and non-peak hours for each store.

Purpose :- Understand customer spending patterns to adjust pricing or promotions accordingly.

*/

-- Ans 5 --
Select store_id,
       store_location,
	   product_category,
	   avg(CASE when transaction_time between '07:00:00' and '09:00:00' 
	             then transaction_qty * unit_price 
	             end) as average_revenue_peak_hours,
	   avg(CASE when transaction_time not between '07:00:00' and '09:00:00' 
	             then transaction_qty * unit_price 
				 end) as average_non_revenue_peak_hours
from Coffee_Shop_Sales
group by store_id , store_location , product_category;

/*

VI) Price Variability Analysis:

Product with the Most Price Fluctuations :-

6) Retrieve the product that has the largest difference between its highest and lowest price across all transactions.

Purpose :- Identify pricing inconsistencies or opportunities for price stabilization.

*/

-- Ans 6 --
Select product_id,
       product_type,
	   product_category,
	   product_detail,
	   max(unit_price) - min(unit_price) as price_fluctuations
from Coffee_Shop_Sales
group by product_id , product_type ,product_category, product_detail
order by price_fluctuations desc limit 1;

/* 

VII) Product Availability Across All Stores :-

Products Sold in Every Store at Least Once :-

7) List all products that have been sold in every store at least once.

Purpose :- Recognize core products that are essential across all locations.

*/

-- Ans 7 -- 
SELECT product_detail
FROM Coffee_Shop_Sales
GROUP BY product_detail
HAVING COUNT(DISTINCT store_id) = (SELECT COUNT(DISTINCT store_id) FROM Coffee_Shop_Sales);